### ISSUE TITLE
Tiff's patches are broken with latests commits of config.sub

### ISSUE THREAD

**Issue by flipacholas** [ps3dev/ps3libraries#34]
The project can't be built anymore, I think `010-tiff-3.9.4.sh` may be the culprit since it's the one downloading files from config.git using the last commit.

Log is:

```
patching file config/config.sub
Hunk #1 FAILED at 865.
1 out of 1 hunk FAILED -- saving rejects to file config/config.sub.rej
patching file contrib/iptcutil/iptcutil.c
../scripts/010-tiff-3.9.4.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
ERROR: Could not run the toolchain script.
```

I don't know what the contributors think it would be better: Fix the patches or change the script to use a past commit?

**Comment by zeldin** [comment]
Thanks for reporting.  I updated the patch.  Locking to an older commit of config.git would just bring the old problem back, that when new arches emerge you can't use them as host for building ps3dev...

**Comment by rstevens011** [comment]
The patch still fails to run as of the latest commit from the config.sub repo:
```
<SNIP>
tiff-3.9.4/tools/tiffgt.c
patching file config/config.sub
Hunk #1 FAILED at 1038.
1 out of 1 hunk FAILED -- saving rejects to file config/config.sub.rej
patching file contrib/iptcutil/iptcutil.c
../scripts/010-tiff-3.9.4.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
ERROR: Could not run the toolchain script.
```

**Comment by zeldin** [comment]
Thanks for reporting.  It turns out that the change in config.sub has been superfluous since commit ded3194, so I simply removed it to avoid further issues.  :grinning:
